[build]
  publish = "face-recognition/static"
  command = "docker build -t face-recognition-app ."

[[plugins]]
  package = "@netlify/plugin-docker"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
